# Generated by Django 5.2.1 on 2025-05-23 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='doc_identity',
            new_name='doc_number',
        ),
    ]
