# Generated by Django 5.2.1 on 2025-06-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_alter_address_user_alter_card_user_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='date_expired',
        ),
        migrations.AddField(
            model_name='card',
            name='exp_month',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='exp_year',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
