# Generated by Django 5.2.1 on 2025-07-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reservations', '0002_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='people',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default=999999999, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservationstatus',
            name='status',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
