# Generated by Django 5.2.1 on 2025-06-29 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default='Pendiente', on_delete=django.db.models.deletion.CASCADE,
                                    to='order.orderstatus'),
        ),
    ]
