# Generated by Django 5.2.1 on 2025-07-16 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cant_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 16, 7, 0, 40, 62354, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
